import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import AuthSessionProvider from "@/providers/auth-session-provider";
// import "./globals.css";
import AlertModal from "@/_components/modals/alert-modal/AlertModal";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthSessionProvider>{children}</AuthSessionProvider>
        <AlertModal></AlertModal>
      </body>
    </html>
  );
}
