export enum MODAL_BUTTON_TYPE_ENUM {
  BUTTON_ONE = 'BUTTON_ONE',
  BUTTON_TWO = 'BUTTON_TWO',
  BUTTON_TWO_RATIO = 'BUTTON_TWO_RATIO',
}

export const CONST_MODAL_BUTTON_TYPE_ENUM = Object.values(
  MODAL_BUTTON_TYPE_ENUM,
);
